"""follower_followed

Revision ID: 565202633e0c
Revises: 4ba6e3f08f40
Create Date: 2024-12-02 10:24:51.480992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565202633e0c'
down_revision = '4ba6e3f08f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
